### ISSUE TITLE
Limiter la carte (ou pas)

### ISSUE THREAD

**Issue by haidaraM** [LoicTouzard/MapIf#1]
Yo.

ça serait peut être pas mal de limiter la zone visible de la carte.

![capture d ecran 2016-05-23 a 01 14 31](https://cloud.githubusercontent.com/assets/9849996/15457128/04c854de-2084-11e6-8fd5-609c572f54a0.png)

**Comment by LoicTouzard** [comment]
En effet trop dézoomer ne sert à rien. Le zoom minimal a été mis au niveau 2.
Commit : 09d1d6e
Merci du retour !

**Comment by LoicTouzard** [comment]
09d1d6e
