### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by koromodako** [LoicTouzard/MapIf#11]
En fait, le site est accessible en HTTPS donc il faut effectuer les modification suivantes : 
- dans le back rediriger la racine pour utiliser HTTPS

```
@app.before_request
def before_request():
    if request.url.startswith('http://'):
        url = request.url.replace('http://', 'https://', 1)
        code = 301
        return redirect(url, code=code)
```
- dans le front requêter l'API en HTTPS

**Comment by LoicTouzard** [comment]
C'est tout ce qu'il y a à faire ?
Ok. Alors c'est une priorité.

**Comment by koromodako** [comment]
Ce problème sera résolu prochainement et intégré au prochain déploiement.
