### ISSUE TITLE
Indiquer le prix de la pinte à la destination

### ISSUE THREAD

**Issue by ghost** [LoicTouzard/MapIf#13]

**Comment by niosega** [comment]
@LoicTouzard Il y a une route pour que tu puisse mettre à jour le prix de la pinte pour une location. 
Je te laisse le faire comme tu le souhaites sur le front.
![four-hands-holing-pints-of-beer](https://cloud.githubusercontent.com/assets/6972578/15887489/dc5901b0-2d62-11e6-96c6-cb74d1ccad63.jpg)

**Comment by LoicTouzard** [comment]
Idée abandonnée.. Pour le moment tout du moins.
