### ISSUE TITLE
Hachage du mot de passe.

### ISSUE THREAD

**Issue by LoicTouzard** [LoicTouzard/MapIf#14]
Actuellement le hash du mot de passe se fait par SHA 256.
J'ouvre cette issue pour discuter du fait qu'il faille ajouter un `sel`.
@halflings et @PandiPanda69 pourront prendre part à la discussion en etant les initiateurs.

**Comment by LoicTouzard** [comment]
Les mots de passes peuvent-ils être retrouvés via un dictionnaire ou un site de ce genre  https://md5hashing.net/hash/sha256 ?

Si un sel doit etre utilisé, `bcrypt` est compatible Python 3.3 : https://pypi.python.org/pypi/bcrypt/2.0.0

**Comment by koromodako** [comment]
La librairie `bcrypt` semble en effet une alternative intéressante à la fonction de hachage actuellement utilsée (SHA256). Néanmoins, la migration de l'ancienne fonction à la nouvelle nécessiterait malgré un temps de développement certains les phases étant:
1. ajout d'une colonne pour stocker le nouveau hash,
2. développement de l'algorithme pour tester l'ancien hash et ajouter le nouveau si l'ancien est valide avec le mot de passe fourni.
3. et finalement supprimer l'ancienne colonne de la table.

Il est donc intéressant de se poser la question de l'utilité d'une telle modification. Une courte analyse de risque permet de dégager les faits suivants:

Deux attaquants sur cet atout:
1. les **développeur de mapif**:
   1. ont **accès aux hachés** mais aussi **au(x) sel(s)** si il y en a (modification du code en production pour récupérer les sels générés, par utilisateur, si nécessaire)
   2. l'**attaque par dictionnaire** est donc **toujours possible** moyennant la génération d'un dictionnaire de hachés à partir des wordlists présentes sur Internet et en ajoutant le(s) sel(s) connu(s) à ces wordlists. Un peu long mais pas impossible et très simple (génération des hachés distribuable).
2. un **attaquant externe** (scénario plus probable)
   1. l'attaquant doit d'abord **obtenir l'accès** aux mots de passe hachés
      1. il doit pour cela **obtenir un accès SSH** à l'application en ajoutant au préalable sa clé publique à la collection de clés permettant l'accès (ce qui est **_très peu probable**_),
      2. ou parvenir à dumper la table de la base en réalisant une injection quelconque sur le site. La **_probabilité d'une injection réussie est très faible**_ étant donné que le site ne propose **pas d'upload**. Que les **champs de saisie** sont **filtrés** côté serveur. Et que les **fonctions** de traitement de templates **vulnérables** aux template injections ne sont **pas utilisées** dans ce projet. Aucune requête SQL injectable car le projet utilise un ORM dont les librairies échappe les paramètres passés aux requête (psycopg2).
   2. attaque des mots de passe
      1. si l'attaquant a obtenu l'accès SSH il a également accès au(x) sel(s) (cf. cas des développeurs),
      2. si l'attaquant a réussi à dumper la table, il lui manque le(s) sel(s). 

Le sel n'est donc utile que dans ce dernier cas dont la **_probabilité**_ est, comme expliqué précédemment, **_très faible**_ étant donnée la surface d'attaque extrêmement réduite de l'application.

Quelque chose d'autre m'échappe peut être auquel cas je serai heureux qu'on me le fasse remarquer, je serai également ravi que l'on me démontre que le point 2.i.b est discutable. Les problématiques ayant attrait à la sécurité m'intéressent, en effet, énormément et je suis en constante recherche pour en connaitre davantage à ce sujet.

Mais il est vrai que la sécurité totale n'existe pas. Certains sites de commerce stockent encore les mots de passe en clair.

**Comment by LoicTouzard** [comment]
Très bonne analyse selon moi.

Je soumettrais néanmoins une alternative à la migration de solution si elle devait avoir lieu :   
1. **changement de la fonction de hash** :  
   1.1 **conservation** de la methode de hash actuel (première phase)  
   1.2 **hash du resultat** hashé précédemment par une methode avec sel (deuxieme phase)  
2. **update de la colonne** `password` de la table utilisateur en modifiant tous les tuples par leur même valeur hashés avec sel par la deuxième phase.

Le point négatif que j'y vois est la _performance_ mais les requêtes d'inscription et de connexion ne sont pas fréquentes.

Un avis ?

**Comment by halflings** [comment]
Je crois que vous sous-estimez largement la dangerosité du fait d'utiliser une fonction de hash rapide comme sha256 comme mesure de sécurité.

Un salt permet de rendre ces attaques plus complexes, en annulant les attaques de dictionnaires (car il faudrait avoir un dictionnaire par salt, ce qui n'est en général pas faisable car les salts sont générés aléatoirement et la chance d'avoir le bon dictionnaire est quasi-nulle).

Il est possible de décrypter un hash sha256 simplement en faisant un brute-force. C'est une fonction de hash trés rapide, et il faudrait [une seconde pour décrypter toute votre base de donnéees](http://crypto.stackexchange.com/questions/12392/calculation-of-time-to-crack-sha-256-hash).

De la même façon, et même en ayant un salt (voir le lien précédent), il est possible de cracker toute la BdD en passant une seconde par utilisateur.

bcrypt est une fonction de hashage lente et qui demande pas mal de mémoire, ce qui la rend difficilement applicable dans une technique de brute-force. En plus, cette méthode inclue un salt donc les attaques par dictionnaires ne marchent pas.

Pour ce qui est du fait qu'un accés par SSH à votre serveur est trés peu probable parce que vous n'avez pas de fonction upload, vous sous-estimez encore une fois toutes les implications au niveau sécurité. Il se peut que votre serveur HTTP ai une faille, que l'un de vous publie une clé par erreur sur Github, qu'il y ait un malware sur votre ordi, etc. ; Le but du cryptage de mot de passes est justement d'être prêt au pire cas, et de ne rien risquer même si quelqu'un a accés à votre base de données (avec ses salts, mot de passes cryptés, etc.).

**Comment by koromodako** [comment]
Merci pour ces remarques. 

Comme l'indique le label **enhancement**, nous envisageons d'intégrer cette amélioration dans une future release.

**Comment by koromodako** [comment]
@halflings : merci pour le conseil que nous avons pris en compte dans la dernière release. Le hachage du mot de passe est maintenant réalisé ici :
https://github.com/LoicTouzard/MapIf/blob/master/src/utils/db.py#L261

La passphrase hachée stockée est le résultat du `sha256` sur lequel un `bcrypt.hashpw` est appliqué (pour simplifier la mise à jour de la base). Le temps de calcul de `sha256` étant négligeable devant celui de `bcrypt` cela devrait suffire pour l'instant.

Nous tenterons de faire évoluer la complexité du hachage au même rythme que les progrès en matière brute force.
