### ISSUE TITLE
Erreur d'installation des dépendances PostgreSQL

### ISSUE THREAD

**Issue by MathisHammel** [LoicTouzard/MapIf#16]
J'ai une erreur lors de l'install pip : `Error: pg_config executable not found.` Le fix est dans #15 

(Je fais cet issue pour le hacktoberfest, sinon j'aurai pas mon T-shirt lel)

**Comment by LoicTouzard** [comment]
Closed donc.
Je veux la moitie du tee shirt !

**Comment by MathisHammel** [comment]
https://hacktoberfest.digitalocean.com/
