### ISSUE TITLE
Encodage

### ISSUE THREAD

**Issue by niosega** [LoicTouzard/MapIf#2]
Problème avec l'encodage des caractères. Exemple avec la ersonne en Chine ou au Japon

**Comment by LoicTouzard** [comment]
Qu'appelles tu un problème d'encodage ? Le fait qu'il y ai des caractères japonais ?
La ville et le pays sont affichés dans la langue locale.

**Comment by niosega** [comment]
Moi j'ai des carrés avec des chiffres dedans. Typiquement un problème d'encodage.
![lolo](https://cloud.githubusercontent.com/assets/6972578/15499366/241eab28-21a4-11e6-82ac-ed5a54f23721.png)
Avec Firefox et avec Chromium.

Toi tu as des caractères cohérents ? Parce que du coup c'est peut etre mon navigateur.

**Comment by LoicTouzard** [comment]
Je vois les bons caractères sur la carte.

![image](https://cloud.githubusercontent.com/assets/9950139/15500081/76149a3e-21a7-11e6-9c7b-ab0c4264a5de.png)
Je suis sur Chrome 49.

**Comment by niosega** [comment]
Firefox 46.0.1 et Chromium 50

**Comment by ghost** [comment]
Avec IE6 ca buggue un peu sur le penjabi traditionnel.

**Comment by koromodako** [comment]
@niosega : quel OS stp ?

**Comment by niosega** [comment]
Je suis sous arch 64 bits.

**Comment by koromodako** [comment]
As-tu vérifié ta `$> locale` ? Pour information :  `LANG=fr_FR.UTF-8` chez moi.
Vérifie que les paquets de fonts sont installés : `xorg-fonts-encodings 1.0.4-4`
Quel environnement de bureau as-tu ?

**Comment by niosega** [comment]
Tous est ok ! mais si le problème est que chez moi, c'estok !
