### ISSUE TITLE
Mapif a t'il un futur ?

### ISSUE THREAD

**Issue by robinroyer** [LoicTouzard/MapIf#20]
Quid d'ouvrir "MapIF" à tous les départements  de l'Insa Lyon (voir toutes les INSA à terme ??) ?
...De demander une subvention annuelle pour son hébergement ? 💸
...De mettre en place un handover avec l'équipe de l'AEDI pour assurer une maintenance du projet (et pousser les promos entrantes à y contribuer)?
... D'une extension de fureteur mettre à jour la localisation ? **#CoucouLaNSA**

Il y a t'il des rêves de grandeur ou ce n'est pas du tout le but et je m'égare? ☀️

**Comment by LoicTouzard** [comment]
Merci de l’intérêt que tu portes au projet et au soucis de son évolutivité dont tu nous fait part. Voici donc mes réponses à tes questions.


> Quid d'ouvrir "MapIF" à tous les départements de l'Insa Lyon (voir toutes les INSA à terme ??) ?

Le projet, originellement, était juste destiné à la promotion 2017 du département IF de l'INSA de Lyon. Le développement avait été en quelque sorte orienté dans ce sens.
Puis ça a rapidement et sans trop de modifications été ouvert à tout le département IF, la seule modification à été d'ajouter une année de promotion.

Ouvrir "_MapIF_" comme tu le mets avec guillemets à tout l'INSA n'a pas été envisagé, mais est envisageable. Cependant cela nécessiterait quelques modifications dues aux nouvelles problématiques qu'apporterait un passage à l'échelle : 

-  Le nom peut il rester _MapIF_ ? Devra-t-il s'orienter vers quelque chose de plus général à l'INSA, voire complètement neutre vis-a-vis de qui l'utilise.
- L'augmentation du nombre de champs demandé à l'inscription : quel département, quel INSA. Ou d'une manière plus globale, à quel groupe vous rattachez vous.
- La visibilité sur la carte, avec un nombre important d'utilisateurs, il devient nécessaire de trouver une bonne manière d'afficher beaucoup d'utilisateurs au même endroit. Le clustering est déjà présent pour les utilisateurs proche, mais l'affichage de beaucoup d'utilisateurs à une même localisation laisse à désirer.
- Les filtres et la recherche, pour suivre au problème de la visibilité, ces deux options sont je pense obligatoire afin de garder une utilisation agréable et pratique de l'interface.
- Sécurité, cohérence. Plus de d'utilisateurs signifie plus de visibilité, mais également plus de troll. Il n'existe pour l'instant aucune manière de vérifier l'appartenance d'un utilisateur à quelconque groupe. Aucune manière de le prouver non plus. Donc cela ouvre potentiellement le site à de nombreux faux comptes, fausse localisations.

Il y a surement d'autres points qui méritent d'être amélioré avant un passage à l'échelle convenable (des idées ?).


> ...De demander une subvention annuelle pour son hébergement ?

Dans le cas d'une ouverture à l'INSA, c'est comme leur offrir un service. Hors pour le moment je ne considère pas se service comme étant d'une qualité suffisante (peut-être mon point de vue est biaisé car je l'ai développé et que je serais alors trop critique). Mais si dans un avenir, il existait une version de MapIF dont je suis pleinement satisfait, qui aura été adapté à la globalité de l'INSA, dont les utilisateurs approuvent le concept et adhère. Alors, je suis prêt à leur montrer ce qu'il en est du projet, et leur proposer contre une subvention annuelle d'hébergement (même si c'est une subvention dérisoire, ça serait plus pour d'une valeur symbolique pour service rendu). Par contre offrir un service serait également proposer une maintenance avec, qui le fera et sur quoi cela porte sont des questions auxquelles il faut répondre aussi.

 
> ...De mettre en place un handover avec l'équipe de l'AEDI pour assurer une maintenance du projet (et pousser les promos entrantes à y contribuer)?

Voilà ce qui pourrait être une réponse au _QUI_ fera la maintenance. Le projet est open source, donc c'est effectivement possible que l'AEDI s'occupe de la maintenance, au même titre que le fameux _site web de l'AEDI_ et _shareif_. On peut considérer que l'AEDI appréciera de maintenir ce projet mais sûrement que si cela ne concerne que les IF ou l'INSA Lyon. Je ne suis plus à l'AEDI, et je ne leur en ai pas parlé non plus pour le moment. Cette décision dépendra directement d'eux, mais encore une fois je préfère avoir un projet plus abouti avant de déléguer la maintenance à quelqu'un. Quoi qu'il en sois l'AEDI étant directement concernée par ce qui touche à ses étudiant d'IF, c'est clairement une solution pouvant amener une pérennité au projet MapIF.

>  ... D'une extension de fureteur mettre à jour la localisation ? #CoucouLaNSA

Quelle serait les fonctionnalités les fonctionnalité d'un plugin pour navigateur ? Détecter si tu as changé de localisation (#CoucouLaNSA) et te proposer de le mettre à jour sur MapIF ?
C'est pas du tout prévu, je n'aime pas trop l'utilisation de plugin navigateurs, mais c'est personnel.
Cette remarque amène une autre problématique : la cohérence des donnée dépend entièrement des utilisateurs, et pour la conserver il faut que les utilisateurs se souvienne de MapIF après le jour de leur première utilisation. C'est un moyen, le rappel/newsletter par mail tout les 6 mois peut en être un aussi.

----

Pour résumer, je dois avouer que cela fait quelques mois que je n'ai pas travailler sur ce projet. Le réveiller avec une question comme _Quid d'une évolutivité par ouverture à d'autres utilisateurs_ me tente, et potentiellement me re-motive à travailler sur ce projet. Une passage à l'échelle de l'INSA n'est obligé de se faire en passant par la direction de communication de l'INSA, mais ça donnerais une certaine légitimité. Il en est de même pour la délégation du projet à l'AEDI.
Le problème majeur que j'ai avec un passage à l'échelle est qu'à l'heure actuelle, le projet n'est pas prêt pour ça. Et il nécessite un certain travail avant de l'être. D'autant plus que quand je regarde ce projet il me semble dépassé technologiquement (pas le concept attention !). C'est sans doute le sentiment que portent la plupart des développeurs web envers leurs anciens projets, à cause de l'évolutivité trop rapide des techno de ce domaine.

En une ligne : L'ouverture et l'officialisation, oui ça me donne envie ! Mais il y a beaucoup de travail.

**Comment by LoicTouzard** [comment]
Coming back with some new features soon.
