### ISSUE TITLE
Impossible de choisir Passau, Allemagne

### ISSUE THREAD

**Issue by mgaillard** [LoicTouzard/MapIf#23]
Je n'arrive pas à rechercher la ville de Passau en Allemagne. Lorsque je regarde les données JSON retournées il y a des résultats pour Passau mais l'interface ne les propose pas. J'ai essayé d'envoyer une requête POST à la main pour changer ma localisation mais j'ai une erreur 500 sûrement parce que j'ai pas respecté le protocole.

**Comment by koromodako** [comment]
Ok je confirme qu'il y a un problème. Ce sera patché avec la prochaine version mais le déploiement n'est pas prévu pour tout de suite...
Il va falloir patienter un petit peu. Tu seras notifié dès que c'est déployé.

**Comment by mgaillard** [comment]
C'est pas limité à cette ville, j'en ai essayé plein d'autres et ça ne fonctionne pas. Pour le moment je me suis mis à Salzweg.

**Comment by koromodako** [comment]
Ok ce doit un être un filtre sur les résultats de nominatim qui est trop puissant. On va essayer d'alleger les contraintes.

**Comment by LoicTouzard** [comment]
Corrigé, ça sera dans le prochain déploiement de version.
