### ISSUE TITLE
Carte - répétition de markers

### ISSUE THREAD

**Issue by niosega** [LoicTouzard/MapIf#3]
Quand on déplace la carte sur le coté, les markers n'apparaissent pas. Il faudrait bloquer la translation de la carte, comme cela a été fait pour le zoom.

**Comment by haidaraM** [comment]
check ça : http://leafletjs.com/reference.html#map-setmaxbounds. C'est ce que j'avais fait pour centrer la carte sur la France

**Comment by LoicTouzard** [comment]
J'irai jeter un coup d'oeil.
Cette propriété http://leafletjs.com/reference.html#tilelayer-nowrap m'a aussi l'air intéressante. Je verrais ce qui est le mieux.

**Comment by haidaraM** [comment]
je ne connaissais pas celle là... ça à l'air d'être ça je crois bien
