### ISSUE TITLE
Recaptcha resetting

### ISSUE THREAD

**Issue by LoicTouzard** [LoicTouzard/MapIf#6]
Si l'on fait une erreur dans le formulaire d'inscription on ne peut plus envoyer le formulaire car le reCaptcha est invalidé et pour les autres envois sans pour autant pouvoir le revalider. On est obligé d'actualiser la page...
![image](https://cloud.githubusercontent.com/assets/9950139/15567707/0dee6fde-2328-11e6-93cb-3040f9af7394.png)

**Comment by koromodako** [comment]
Un petit [reset](http://stackoverflow.com/questions/3371314/how-to-reload-recaptcha-using-javascript) du captcha devrait suffire ;)
