### ISSUE TITLE
Identifier et filtrer les étudiants par promotion

### ISSUE THREAD

**Issue by cfboscher** [LoicTouzard/MapIf#7]
Pour identifier la promotion d'un étudiant, un label ( + année d'étude si en cours) voire un code couleur pourraient être intéressants (cependant, comment traiter rigoureusement le cas où deux étudiants de promotions différentes se trouvent au même endroit ?)

Il serait également intéressant de pouvoir n'afficher que les étudiants de certaines promotions sur la map. 

Par exemple, une liste des promotions "actives" (toutes par défaut), dans laquelle on peut décocher les promotions qu'on ne souhaite pas afficher.

**Comment by koromodako** [comment]
C'est une excellente idée ! La fonction sera sans doute intégrée dans une version à venir. Merci !
